spring:
  application:
    name: ai-example
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-5
          temperature: 1

server:
  port: 8080